/*
 * Alex Dawson
 * 24-Jan-2020
 * --------------------------------------
 * DnDDice/DnDDIce.java
 */
package dnddice;
import java.util.*;
import java.text.*;
/**
 *
 * @author ktad2
 */
public class DnDDice extends javax.swing.JFrame {

    /**
     * Creates new form DnDDIce
     */
    public DnDDice() {
        initComponents();
    }
    
    public Random random = new Random();
    public SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss");
    public Dice dice;
    public Calculator calc;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        d20Bttn = new javax.swing.JButton();
        d4Output = new javax.swing.JLabel();
        exitBttn = new javax.swing.JButton();
        d12Bttn = new javax.swing.JButton();
        d12Output = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        d10Bttn = new javax.swing.JButton();
        d10Output2 = new javax.swing.JLabel();
        d10Output1 = new javax.swing.JLabel();
        d8Bttn = new javax.swing.JButton();
        d8Output = new javax.swing.JLabel();
        d6Bttn = new javax.swing.JButton();
        d6Output = new javax.swing.JLabel();
        d20Output = new javax.swing.JLabel();
        d4Bttn = new javax.swing.JButton();
        calcLabel = new javax.swing.JLabel();
        num1Input = new javax.swing.JTextField();
        num2Input = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        calcOutput = new javax.swing.JTextArea();
        calcBttn = new javax.swing.JButton();
        plusLabel = new javax.swing.JLabel();
        addRoll1Bttn = new javax.swing.JButton();
        addRoll2Bttn = new javax.swing.JButton();
        addRecentCalcBttn = new javax.swing.JButton();
        clearBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dungeons and Dragons Dice For The Poor");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(102, 0, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/dnddice/assets/icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 0, 0));

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Dungeons and Dragons Dice For The Poor");

        d20Bttn.setText("Roll D20");
        d20Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d20BttnActionPerformed(evt);
            }
        });

        d4Output.setBackground(new java.awt.Color(204, 0, 0));
        d4Output.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d4Output.setForeground(new java.awt.Color(0, 0, 255));
        d4Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d4Output.setText("4");
        d4Output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        exitBttn.setText("Exit");
        exitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBttnActionPerformed(evt);
            }
        });

        d12Bttn.setText("Roll D12");
        d12Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d12BttnActionPerformed(evt);
            }
        });

        d12Output.setBackground(new java.awt.Color(204, 0, 0));
        d12Output.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d12Output.setForeground(new java.awt.Color(0, 0, 255));
        d12Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d12Output.setText("12");
        d12Output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        d10Bttn.setText("Roll D10");
        d10Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d10BttnActionPerformed(evt);
            }
        });

        d10Output2.setBackground(new java.awt.Color(204, 0, 0));
        d10Output2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d10Output2.setForeground(new java.awt.Color(0, 0, 255));
        d10Output2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d10Output2.setText("90");
        d10Output2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        d10Output1.setBackground(new java.awt.Color(204, 0, 0));
        d10Output1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d10Output1.setForeground(new java.awt.Color(0, 0, 255));
        d10Output1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d10Output1.setText("9");
        d10Output1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        d8Bttn.setText("Roll D8");
        d8Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d8BttnActionPerformed(evt);
            }
        });

        d8Output.setBackground(new java.awt.Color(204, 0, 0));
        d8Output.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d8Output.setForeground(new java.awt.Color(0, 0, 255));
        d8Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d8Output.setText("8");
        d8Output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        d6Bttn.setText("Roll D6");
        d6Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6BttnActionPerformed(evt);
            }
        });

        d6Output.setBackground(new java.awt.Color(204, 0, 0));
        d6Output.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d6Output.setForeground(new java.awt.Color(0, 0, 255));
        d6Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d6Output.setText("6");
        d6Output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        d20Output.setBackground(new java.awt.Color(204, 0, 0));
        d20Output.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        d20Output.setForeground(new java.awt.Color(0, 0, 255));
        d20Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d20Output.setText("20");
        d20Output.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        d4Bttn.setText("Roll D4");
        d4Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4BttnActionPerformed(evt);
            }
        });

        calcLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        calcLabel.setForeground(new java.awt.Color(0, 0, 255));
        calcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcLabel.setText("Calculator");

        calcOutput.setColumns(20);
        calcOutput.setRows(5);
        jScrollPane2.setViewportView(calcOutput);

        calcBttn.setText("Calculate");
        calcBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBttnActionPerformed(evt);
            }
        });

        plusLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        plusLabel.setForeground(new java.awt.Color(255, 255, 255));
        plusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plusLabel.setText("+");

        addRoll1Bttn.setText("Add Most Recent Roll");
        addRoll1Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoll1BttnActionPerformed(evt);
            }
        });

        addRoll2Bttn.setText("Add Most Recent Roll");
        addRoll2Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoll2BttnActionPerformed(evt);
            }
        });

        addRecentCalcBttn.setText("Add Most Recent Calculation");
        addRecentCalcBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecentCalcBttnActionPerformed(evt);
            }
        });

        clearBttn.setText("Clear Calculator");
        clearBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d20Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d20Output, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d12Output, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d12Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(d10Output1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d10Output2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(d10Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d8Output, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d8Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d6Output, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d6Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d4Bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d4Output, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num1Input, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(num2Input)
                                    .addComponent(plusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addRoll2Bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addRoll1Bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addRecentCalcBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(calcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(exitBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(calcBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calcLabel)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRoll1Bttn)
                            .addComponent(addRecentCalcBttn))
                        .addGap(2, 2, 2)
                        .addComponent(plusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRoll2Bttn)
                            .addComponent(clearBttn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(d4Output)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d4Bttn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(d6Output)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d6Bttn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(d8Output)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(d8Bttn))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(d20Output)
                                        .addComponent(d12Output)
                                        .addComponent(d10Output1)
                                        .addComponent(d10Output2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(d20Bttn)
                                        .addComponent(d12Bttn)
                                        .addComponent(d10Bttn)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBttn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void d20BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d20BttnActionPerformed
        dice = new Dice("D20", 20, 1, 1);
        d20Output.setText(dice.getRoll());
        txtOutput.append(dice.toString());
    }//GEN-LAST:event_d20BttnActionPerformed

    private void d12BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d12BttnActionPerformed
        dice = new Dice("D12", 12, 1, 1);
        d12Output.setText(dice.getRoll());
        txtOutput.append(dice.toString());
    }//GEN-LAST:event_d12BttnActionPerformed

    private void d10BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d10BttnActionPerformed
        dice = new Dice("D10a", 10, 0, 1);
        d10Output1.setText(dice.getRoll());
        txtOutput.append(dice.toString());
        
        dice = new Dice("D10b", 10, 0, 10);
        d10Output2.setText(dice.getRoll());
        txtOutput.append(dice.toString());
    }//GEN-LAST:event_d10BttnActionPerformed

    private void d8BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d8BttnActionPerformed
        dice = new Dice("D8", 8, 1, 1);
        d8Output.setText(dice.getRoll());
        txtOutput.append(dice.toString());
    }//GEN-LAST:event_d8BttnActionPerformed

    private void d6BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d6BttnActionPerformed
        dice = new Dice("D6", 6, 1, 1);
        d6Output.setText(dice.getRoll());
        txtOutput.append(dice.toString());
    }//GEN-LAST:event_d6BttnActionPerformed

    private void d4BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4BttnActionPerformed
        dice = new Dice("D4", 4, 1, 1);
        d4Output.setText(dice.getRoll());
        txtOutput.append(dice.toString());
    }//GEN-LAST:event_d4BttnActionPerformed

    private void exitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBttnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBttnActionPerformed

    private void addRoll1BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoll1BttnActionPerformed
        num1Input.setText(dice.getRoll());
    }//GEN-LAST:event_addRoll1BttnActionPerformed

    private void addRecentCalcBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecentCalcBttnActionPerformed
        num1Input.setText(calc.getAnswer());
    }//GEN-LAST:event_addRecentCalcBttnActionPerformed

    private void addRoll2BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoll2BttnActionPerformed
        num2Input.setText(dice.getRoll());
    }//GEN-LAST:event_addRoll2BttnActionPerformed

    private void calcBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBttnActionPerformed
        int num1 = Integer.parseInt(num1Input.getText());
        int num2 = Integer.parseInt(num2Input.getText());
        calc = new Calculator(num1, num2);
        calcOutput.append(calc.toString());
    }//GEN-LAST:event_calcBttnActionPerformed

    private void clearBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBttnActionPerformed
        num1Input.setText("");
        num2Input.setText("");
        calcOutput.setText("");
    }//GEN-LAST:event_clearBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DnDDice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DnDDice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DnDDice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DnDDice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DnDDice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecentCalcBttn;
    private javax.swing.JButton addRoll1Bttn;
    private javax.swing.JButton addRoll2Bttn;
    private javax.swing.JButton calcBttn;
    private javax.swing.JLabel calcLabel;
    private javax.swing.JTextArea calcOutput;
    private javax.swing.JButton clearBttn;
    private javax.swing.JButton d10Bttn;
    private javax.swing.JLabel d10Output1;
    private javax.swing.JLabel d10Output2;
    private javax.swing.JButton d12Bttn;
    private javax.swing.JLabel d12Output;
    private javax.swing.JButton d20Bttn;
    private javax.swing.JLabel d20Output;
    private javax.swing.JButton d4Bttn;
    private javax.swing.JLabel d4Output;
    private javax.swing.JButton d6Bttn;
    private javax.swing.JLabel d6Output;
    private javax.swing.JButton d8Bttn;
    private javax.swing.JLabel d8Output;
    private javax.swing.JButton exitBttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField num1Input;
    private javax.swing.JTextField num2Input;
    private javax.swing.JLabel plusLabel;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
